### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nhrones** [josephg/fdb-tuple#9]
I've ported a copy of Tuple.ts to be run with Deno.
What is the best way to attribute this to you?

**Comment by josephg** [comment]
Mmm maybe just give me credit in the readme or code somewhere?

> This code was originally ported from fdb-tuple by Joseph Gentle (link)

**Comment by nhrones** [comment]
Done and Done.  Thanks for thisI  
Deno.Kv in Deno deploy is using FDB.  In the CLI, Deno.Kv uses SQLite as the persistence layer.  Both use FDB-Tuple `multipart` keys.
Unfortunately, Deno does not export its codec written in Rust.
